app_group:
  - read:
      path: /apps/security.eda.nokia.com
      method: GET

intent_targets:
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments/{name}/_targets
      method: GET
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains/{name}/_targets
      method: GET

k8_s_topology_request:
  - create:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments/{name}/_topology
      method: POST
  - create:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains/{name}/_topology
      method: POST

patch:
  - update:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments/{name}
      method: PATCH
  - update:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments/{name}/_revs
      method: GET
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments/{name}/_topology
      method: GET
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments/{name}
      method: DELETE
  - delete:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.security.v1alpha1.keychain:
  - create:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains
      method: POST
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains/{name}
      method: GET
  - update:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains/{name}
      method: PUT

com.nokia.eda.security.v1alpha1.keychain_deployment:
  - create:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments
      method: POST
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments/{name}
      method: GET
  - update:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments/{name}
      method: PUT

com.nokia.eda.security.v1alpha1.keychain_deployment_list:
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/keychaindeployments
      method: GET
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments
      method: GET
  - delete:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments
      method: DELETE

com.nokia.eda.security.v1alpha1.keychain_deployment_deleted_resources:
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychaindeployments/_deleted
      method: GET

com.nokia.eda.security.v1alpha1.keychain_list:
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/keychains
      method: GET
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains
      method: GET
  - delete:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains
      method: DELETE

com.nokia.eda.security.v1alpha1.keychain_deleted_resources:
  - read:
      path: /apps/security.eda.nokia.com/v1alpha1/namespaces/{namespace}/keychains/_deleted
      method: GET

totalPaths: 17
totalSchemas: 61
usedSchemas: 15
unusedSchemas: 46
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - IntentTarget
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - Topology
  - com.nokia.eda.security.v1alpha1.KeychainDeployment_DeletedResourceEntry
  - com.nokia.eda.security.v1alpha1.KeychainDeployment_alarms
  - com.nokia.eda.security.v1alpha1.KeychainDeployment_deviations
  - com.nokia.eda.security.v1alpha1.KeychainDeployment_metadata
  - com.nokia.eda.security.v1alpha1.Keychain_DeletedResourceEntry
  - com.nokia.eda.security.v1alpha1.Keychain_alarms
  - com.nokia.eda.security.v1alpha1.Keychain_deviations
  - com.nokia.eda.security.v1alpha1.Keychain_metadata
